// Package media models private photos attached to an Encounter.
//
// Requirement 003 keeps originals exactly as uploaded: the server validates
// and measures them but never resizes, re-encodes, or strips them, so later
// identification research can evaluate the captured image without hidden
// transformations. Identification states belong to a later requirement.
package media

import (
	"bufio"
	"errors"
	"fmt"
	"image"
	"image/jpeg"
	"image/png"
	"io"
	"mime"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
)

const (
	KindPhoto = "PHOTO"

	// StatusReady media has validated, published bytes. StatusRejected is
	// reserved for future moderation; Requirement 003 never stores a rejected
	// upload (invalid uploads are refused before anything is persisted).
	StatusReady    = "READY"
	StatusRejected = "REJECTED"

	ContentTypeJPEG = "image/jpeg"
	ContentTypePNG  = "image/png"
)

// Upload limits. They are deliberately conservative and explicit:
//
//   - MaxBytes caps the encoded upload (15 MiB).
//   - MaxEdge caps either side of the decoded image.
//   - MaxPixels caps the decoded area, so a tiny compressed payload cannot
//     claim an unreasonable decoded size (a "decompression bomb"). 50 MP
//     covers current phone main sensors (e.g. 8160x6120) while bounding the
//     memory a full decode can take.
const (
	MaxBytes  int64 = 15 << 20
	MaxEdge         = 12000
	MaxPixels       = 50_000_000
)

var (
	ErrNotFound        = errors.New("media not found")
	ErrUnsupportedType = errors.New("Content-Type must be image/jpeg or image/png")
	ErrTypeMismatch    = errors.New("photo content does not match the declared Content-Type")
	ErrTooLarge        = fmt.Errorf("photo must be at most %d bytes", MaxBytes)
	ErrInvalidImage    = errors.New("photo is not a valid JPEG or PNG image")
	ErrDimensions      = fmt.Errorf("photo must be at most %d pixels per side and %d pixels in total", MaxEdge, MaxPixels)
	ErrTooManyPhotos   = fmt.Errorf("an encounter can have at most %d photos", MaxPhotosPerEncounter)
)

// MaxPhotosPerEncounter bounds how much private storage one encounter can
// consume. The camera flow attaches one photo per encounter.
const MaxPhotosPerEncounter = 5

// Media is the metadata of one stored photo. StorageKey is internal: it is
// generated by the server and never part of a response.
type Media struct {
	ID          string
	EncounterID string
	Kind        string
	Status      string
	ContentType string
	ByteSize    int64
	Width       int
	Height      int
	SHA256      string
	StorageKey  string
	CreatedAt   time.Time
}

// Info is what Inspect learns from the bytes themselves.
type Info struct {
	ContentType string
	Width       int
	Height      int
}

// DeclaredType parses a client Content-Type header. The declared type is only
// ever compared with the sniffed type; it is never proof of the content.
func DeclaredType(header string) (string, error) {
	mediaType, _, err := mime.ParseMediaType(header)
	if err != nil {
		return "", ErrUnsupportedType
	}
	switch strings.ToLower(mediaType) {
	case ContentTypeJPEG:
		return ContentTypeJPEG, nil
	case ContentTypePNG:
		return ContentTypePNG, nil
	}
	return "", ErrUnsupportedType
}

var pngSignature = []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}

// Sniff identifies a supported format from its leading magic bytes only.
func Sniff(head []byte) (string, bool) {
	switch {
	case len(head) >= 3 && head[0] == 0xFF && head[1] == 0xD8 && head[2] == 0xFF:
		return ContentTypeJPEG, true
	case len(head) >= len(pngSignature) && string(head[:len(pngSignature)]) == string(pngSignature):
		return ContentTypePNG, true
	}
	return "", false
}

// Inspect validates stored bytes: it sniffs the real format, reads the image
// header, enforces the dimension limits, and then fully decodes the image so
// truncated or malformed content is rejected. open is called twice (header,
// then full decode) and every reader it returns is closed.
func Inspect(open func() (io.ReadCloser, error)) (Info, error) {
	info, err := inspectHeader(open)
	if err != nil {
		return Info{}, err
	}
	r, err := open()
	if err != nil {
		return Info{}, err
	}
	defer r.Close()
	var img image.Image
	if info.ContentType == ContentTypeJPEG {
		img, err = jpeg.Decode(r)
	} else {
		img, err = png.Decode(r)
	}
	if err != nil {
		return Info{}, ErrInvalidImage
	}
	if b := img.Bounds(); b.Dx() != info.Width || b.Dy() != info.Height {
		return Info{}, ErrInvalidImage
	}
	return info, nil
}

func inspectHeader(open func() (io.ReadCloser, error)) (Info, error) {
	r, err := open()
	if err != nil {
		return Info{}, err
	}
	defer r.Close()
	br := bufio.NewReader(r)
	head, _ := br.Peek(len(pngSignature))
	contentType, ok := Sniff(head)
	if !ok {
		return Info{}, ErrInvalidImage
	}
	var cfg image.Config
	if contentType == ContentTypeJPEG {
		cfg, err = jpeg.DecodeConfig(br)
	} else {
		cfg, err = png.DecodeConfig(br)
	}
	if err != nil || cfg.Width <= 0 || cfg.Height <= 0 {
		return Info{}, ErrInvalidImage
	}
	if cfg.Width > MaxEdge || cfg.Height > MaxEdge || int64(cfg.Width)*int64(cfg.Height) > MaxPixels {
		return Info{}, ErrDimensions
	}
	return Info{ContentType: contentType, Width: cfg.Width, Height: cfg.Height}, nil
}

// NewPhoto creates READY photo metadata with a server-generated ID and
// storage key. No client input contributes to the key.
func NewPhoto(encounterID string, info Info, byteSize int64, sha256Hex string, now time.Time) Media {
	id := uuid.NewString()
	ext := ".jpg"
	if info.ContentType == ContentTypePNG {
		ext = ".png"
	}
	return Media{
		ID: id, EncounterID: encounterID, Kind: KindPhoto, Status: StatusReady,
		ContentType: info.ContentType, ByteSize: byteSize, Width: info.Width, Height: info.Height,
		SHA256: sha256Hex, StorageKey: "photos/" + id + ext, CreatedAt: now.UTC().Truncate(time.Microsecond),
	}
}

var storageKeyPattern = regexp.MustCompile(`^photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png)$`)

// ValidStorageKey reports whether key has the exact server-generated shape.
// Stores refuse every other key, so no path can escape the media root.
func ValidStorageKey(key string) bool { return storageKeyPattern.MatchString(key) }
